version: "3"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
  worker:
    build:
      context: .
      dockerfile: Dockerfile.server
  webserver:
    build:
      context: .
      dockerfile: Dockerfile.server
