lockfile = "/tmp/starfish/pid"
log_path = "/tmp/starfish/logs"
scm_path = "/tmp/starfish/scm"
cache_bucket = "eu-dfinity-nix-cache-2-jude"

shell = "/bin/bash"

database_url = "postgres:///starfish"

builders = ["localhost x86_64-linux - 16 1 big-parallel"]

# You should pass these as environment variables in production using STARFISH_SECRETS_* environment variables.
# Default ones are provided here for convenience.
[secrets]
aws_access_key = "invalid-access-key"
aws_secret_key = "invalid-secret-key"
nix_signing_key = "invalid-signing-key"
