lockfile = "/tmp/starfish.pid"
log_path = "/tmp/starfish/logs"
scm_path = "/tmp/starfish/scm"
cache_bucket = "nix-cache-bucket-jude"

shell = "/bin/bash"

signing_key = "no-such-key"
aws_access_key = "no-such-key"
aws_secret_key = "no-such-key"
# base64 encoded "no-such-key"
ssh_private_key = "bm8tc3VjaC1rZXkK"

database_url = "postgres:///starfish"
