# Directory containing log files for nix builds. The host directory mounted to this path should be shared between the worker and the webserver.
log_path = "/var/log/starfish"

# Hopefully self-explanatory.
listen_port = 8000
listen_address = "0.0.0.0"

# Postgres `pg_connect`-compatible URI.
database_url = "postgres://starfish:starfish@postgres/starfish"

# Directory containing built JS, CSS and image assets for the web frontend. You probably don't need to change this.
static_root = "/share/starfish"
