lockfile = "/var/run/starfish/pid"
log_path = "/var/log/starfish"
scm_path = "/var/lib/starfish/scm"

build_shell = "/nix/var/nix/profiles/default/bin/bash"

database_url = "postgres://starfish:starfish@postgres/starfish"
builders = ["localhost x86_64-linux - 16 1 big-parallel"]

[publish]
type = "s3"
bucket = "eu-dfinity-nix-cache-2"
region = "eu-central-1"
access_key = "invalid"
secret_key = "invalid"
nix_signing_key = "invalid"
