lockfile = "/var/run/starfish/pid"
log_path = "/var/lib/starfish/logs"
scm_path = "/var/lib/starfish/scm"

build_shell = "/nix/var/nix/profiles/default/bin/bash"

listen_address = "0.0.0.0"

database_url = "postgres://starfish:starfish@db/starfish"

[publish]
type = "s3"
bucket = "nix-cache-bucket"
region = "eu-central-1"
access_key = "invalid"
secret_key = "invalid"
nix_signing_key = "invalid"
