lockfile = "/tmp/starfish/pid"
log_path = "/tmp/starfish/logs"
scm_path = "/tmp/starfish/scm"

build_shell = "/bin/bash"

database_url = "postgres:///starfish"
builders = ["localhost x86_64-linux - 10 1 big-parallel"]

[publish]
type = "none"
