lockfile = "/var/run/starfish/pid"
log_path = "/var/lib/starfish/logs"
scm_path = "/var/lib/starfish/scm"
cache_bucket = "nix-cache-bucket"

shell = "/nix/var/nix/profiles/default/bin/bash"

listen_address = "0.0.0.0"

database_url = "postgres://starfish:starfish@db/starfish"
